// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9m1wuFTSwDyvj3VvxjeuQDwQNJp8zZco',
    appId: '1:688438518531:web:73b518722745ad9e27ff36',
    messagingSenderId: '688438518531',
    projectId: 'empatia-34400',
    authDomain: 'empatia-34400.firebaseapp.com',
    databaseURL: 'https://empatia-34400-default-rtdb.firebaseio.com',
    storageBucket: 'empatia-34400.firebasestorage.app',
    measurementId: 'G-METWV1ZZ3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCvISukzxf0peSrVccvzMn2l5Kt2pQnEo',
    appId: '1:688438518531:android:6a8fc88d5496bce927ff36',
    messagingSenderId: '688438518531',
    projectId: 'empatia-34400',
    databaseURL: 'https://empatia-34400-default-rtdb.firebaseio.com',
    storageBucket: 'empatia-34400.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwwM9d-Mk6dSV7UjMvTMP-ybRxOQEWZ7w',
    appId: '1:688438518531:ios:e37de2703041b6b827ff36',
    messagingSenderId: '688438518531',
    projectId: 'empatia-34400',
    databaseURL: 'https://empatia-34400-default-rtdb.firebaseio.com',
    storageBucket: 'empatia-34400.firebasestorage.app',
    iosBundleId: 'com.example.empatia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwwM9d-Mk6dSV7UjMvTMP-ybRxOQEWZ7w',
    appId: '1:688438518531:ios:e37de2703041b6b827ff36',
    messagingSenderId: '688438518531',
    projectId: 'empatia-34400',
    databaseURL: 'https://empatia-34400-default-rtdb.firebaseio.com',
    storageBucket: 'empatia-34400.firebasestorage.app',
    iosBundleId: 'com.example.empatia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9m1wuFTSwDyvj3VvxjeuQDwQNJp8zZco',
    appId: '1:688438518531:web:567ef7999103a02227ff36',
    messagingSenderId: '688438518531',
    projectId: 'empatia-34400',
    authDomain: 'empatia-34400.firebaseapp.com',
    databaseURL: 'https://empatia-34400-default-rtdb.firebaseio.com',
    storageBucket: 'empatia-34400.firebasestorage.app',
    measurementId: 'G-2CJ5TXXC1Q',
  );
}
